### ISSUE TITLE
metaflow 还没正式开源吗？

### ISSUE THREAD

**Issue by theseusyang** [metaflowys/metaflow#1]
metaflow 还没正式开源吗？

**Comment by naughtyGitCat** [comment]
is there any open-source code other than ads?

**Comment by naughtyGitCat** [comment]
@rvql @sharang

**Comment by sharang** [comment]
@naughtyGitCat @theseusyang we are pushing code now :)

The first RC version will be released at the end of June, and the stable version will be released in mid-July.

here is our future plan: https://github.com/metaflowys/metaflow#milestones
