### ISSUE TITLE
Projects to merge

### ISSUE THREAD

**Issue by rvql** [metaflowys/metaflow#2]
- [x] agent
   - [x] @rvql sha1: 5c825463b5e899051ce5239a837a20cbf66129a0
   - [x] @rvql lock trident-rs@gitlab
- [x] server/querier, server/controller, cli
   - [x] @SongZhen0704 sha1: 
   - [x] @SongZhen0704 lock metaflow@gitlab
- [x] server/ingester
   - [x] @lzf575 sha1:
   - [x] @lzf575 lock metaflow@gitlab
- [x] server/libs
   - [x] @yuanchaoa sha1: ea78e40ab6e631c948594642a0da1c9bcd81467a
   - [x] @yuanchaoa lock droplet-libs@gitlab
- [x] message
   - [x] @yuanchaoa sha1: 81e0013f1162af2c934a0a0024c2c910a645e661
   - [x] @yuanchaoa lock message@gitlab

**Comment by lzf575** [comment]
droplet  326dc3f2
